// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Qr5C28_hqBbwjfdqrncGK7JHx-TLytQ',
    appId: '1:301300838949:web:8b0c8b7eb2420cea7e05cc',
    messagingSenderId: '301300838949',
    projectId: 'auth-task-ffe82',
    authDomain: 'auth-task-ffe82.firebaseapp.com',
    storageBucket: 'auth-task-ffe82.firebasestorage.app',
    measurementId: 'G-55T7MNL2YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA55UcGJT_yQujhFabzz69eQ152B59LzZo',
    appId: '1:301300838949:android:efe921c1ec64fc2d7e05cc',
    messagingSenderId: '301300838949',
    projectId: 'auth-task-ffe82',
    storageBucket: 'auth-task-ffe82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRUxJhDnvcnjIsKmeLs3T2P8ZeIAt_hE',
    appId: '1:301300838949:ios:cc4afea6538d7d8f7e05cc',
    messagingSenderId: '301300838949',
    projectId: 'auth-task-ffe82',
    storageBucket: 'auth-task-ffe82.firebasestorage.app',
    iosBundleId: 'com.example.authTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRUxJhDnvcnjIsKmeLs3T2P8ZeIAt_hE',
    appId: '1:301300838949:ios:cc4afea6538d7d8f7e05cc',
    messagingSenderId: '301300838949',
    projectId: 'auth-task-ffe82',
    storageBucket: 'auth-task-ffe82.firebasestorage.app',
    iosBundleId: 'com.example.authTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Qr5C28_hqBbwjfdqrncGK7JHx-TLytQ',
    appId: '1:301300838949:web:b08d9ca55272cc9b7e05cc',
    messagingSenderId: '301300838949',
    projectId: 'auth-task-ffe82',
    authDomain: 'auth-task-ffe82.firebaseapp.com',
    storageBucket: 'auth-task-ffe82.firebasestorage.app',
    measurementId: 'G-M1KLB1XVEE',
  );
}
